export const availableRegions = [
  'chinaeast2',
  'uaenorth',
  'usgovvirginia',
  'australiacentral2',
  'canadaeast',
  'northcentralus',
  'westindia',
  'chinanorth',
  'koreacentral',
  'francecentral',
  'germanynorth',
  'germanycentral',
  'australiacentral',
  'usgoviowa',
  'japaneast',
  'southcentralus',
  'usdodcentral',
  'eastus',
  'uaecentral',
  'australiasoutheast',
  'centralus',
  'centralindia',
  'westcentralus',
  'germanywestcentral',
  'usgovarizona',
  'eastus2',
  'usdodeast',
  'southeastasia',
  'francesouth',
  'koreasouth',
  'switzerlandnorth',
  'norwayeast',
  'southafricanorth',
  'ukwest',
  'switzerlandwest',
  'swedencentral',
  'chinaeast',
  'japanwest',
  'brazilsouth',
  'westus3',
  'northeurope',
  'australiaeast',
  'southindia',
  'westus',
  'norwaywest',
  'canadacentral',
  'westeurope',
  'southafricawest',
  'eastasia',
  'germanynortheast',
  'chinanorth2',
  'westus2',
  'usgovtexas',
  'uksouth',
] as const;
export const powerStateNames = [
  'Filter',
  'Running',
  'Restarting',
  'Stopped',
  'Starting',
  'Creating',
] as const;
export const powerStateValues = [
  'default',
  'running',
  'restarting',
  'stopped',
  'starting',
  'creating',
] as const;
export const sortOptionsNames = ['Sort', 'Name', 'Ip Address'] as const;
export const sortOptionsValues = ['default', 'name', 'ipAddress'] as const;
export const sortOrderNames = ['Ascending', 'Descending'] as const;
export const sortOrderValues = ['asc', 'desc'] as const;
export const groupByOptionsNames = ['Group By', 'Region', 'Status'] as const;
export const groupByOptionsValues = ['default', 'region', 'status'] as const;
